#!/usr/bin/env python3

import fileinput

def operate(stack, line):
    token = line.strip()

    if token in "+-*/":
        op2 = stack.pop()
        op1 = stack.pop()
        if token == '+':
            result = op1 + op2
        elif token == '-':
            result = op1 - op2
        elif token == '*':
            result = op1 * op2
        elif token == '/':
            result = op1 / op2

        stack.append(result)
    else:
        stack.append(float(token))

def main():
    stack = []

    for line in fileinput.input(encoding="utf-8"):
        operate(stack, line)

    print(stack.pop())

if __name__ == "__main__":
    main()
